<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Page;
use App\Models\User;
use Illuminate\Support\Str;

class PageSeeder extends Seeder
{
    public function run(): void
    {
        $author = User::first();

        // ✅ Combined config (template + description)
        $pages = [
            'Home' => [
                'template' => 'home',
                'description' => 'Welcome to our homepage',
            ],
            'About Us' => [
                'template' => 'about',
                'description' => '<p>At <strong>Jovial Vision</strong>, we believe that every accessory tells a story. Founded by <strong>Dikssha Mehtta</strong>, our brand brings you beautifully handcrafted bracelets and lifestyle pieces designed to add positivity, style, and confidence to your everyday life. Each creation is made with care, passion, and a vision to inspire joy and self-expression.</p>',
            ],
            'Contact Us' => [
                'template' => 'contact',
                'description' => 'Get in touch with us',
            ],
            'Bulk Enquiry' => [
                'template' => 'bulkenquiry',
                'description' => '',
            ],
            'Privacy Policy' => [
                'template' => 'default',
                'description' => '<div>
                                    <p><strong>Information We Collect</strong></p>
                                    <p>Personal Information: We collect personal details such as your name,<br>email address, shipping address, phone number, and payment information when you make a purchase, create an account, or contact us.</p>
                                    <p>Non-Personal Information: We may collect non-personal data such as browser type, operating system, and browsing behavior to improve our website and services.</p>
                                    <p><strong>How We Use Your Information</strong></p>
                                    <p>To Process Orders: We use your personal information to process and fulfill your orders.<br>To Communicate: We use your contact information to send you updates about your order, respond to inquiries, and send promotional materials if you have opted in.<br>To Improve Our Services: We analyze non-personal information to understand user behavior and enhance our website’s performance.</p>
                                    <p><strong>Information Sharing</strong></p>
                                    <p>Third-Party Service Providers: We may share your information with third-party service providers who assist us in operating our website, processing payments, and delivering orders.<br>Legal Requirements: We may disclose your information if required by law or to protect our rights.</p>
                                    <p><strong>Data Security</strong></p>
                                    <p>We implement appropriate security measures to protect your personal information from unauthorized access, alteration, disclosure, or destruction.</p>
                                    <p><strong>Your Rights</strong></p>
                                    <p>Access and Correction: You have the right to access and correct your personal information. You can update your account details through our website.<br>Opt-Out: You can opt-out of receiving promotional emails by following the unsubscribe instructions in the emails.</p>
                                    <p><strong>Changes to This Policy</strong></p>
                                    <p>We may update this Privacy Policy from time to time. Any changes will be posted on this page, and the revised date will be indicated at the top of the policy.</p>
                                </div>',
            ],
            'Terms & Conditions' => [
                'template' => 'default',
                'description' => '<div>
                                    <p>This document is an electronic record in terms of the Information Technology Act, 2000, and rules thereunder as applicable, and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
                                    <p>This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011, that require publishing the rules and regulations, privacy policy, and Terms of Use for access or usage of the domain name jovialvision.com (“Website”), including the related mobile site and mobile application (hereinafter referred to as “Platform”).</p>
                                    <p>The Platform is owned by Jovial Vision a company incorporated under the Companies Act, 1956, with its registered office at 23b/5, New Rohtak Road, Near Liberty Cinema, Dev Nagar Karol Bagh, New Delhi 110005 Opp. Bikaner. (hereinafter referred to as “Platform Owner,” “we,” “us,” or “our”).</p>
                                    <p>Your use of the Platform, services, and tools are governed by the following terms and conditions (“Terms of Use”) as applicable to the Platform, including the applicable policies which are incorporated herein by way of reference. If you transact on the Platform, you shall be subject to the policies that are applicable for such transactions. By mere use of the Platform, you shall be contracting with the Platform Owner, and these terms and conditions, including the policies, constitute your binding obligations with the Platform Owner.</p>
                                    <p>These Terms of Use relate to your use of our website, goods (as applicable), or services (as applicable) (collectively, “Services”). Any terms and conditions proposed by you which are in addition to or which conflict with these Terms of Use are expressly rejected by the Platform Owner and shall be of no force or effect. These Terms of Use can be modified at any time without assigning any reason. It is your responsibility to periodically review these Terms of Use to stay informed of updates.</p>
                                    <p>For the purpose of these Terms of Use, wherever the context so requires, “you”, “your,” or “user” shall mean any natural or legal person who has agreed to become a user/buyer on the Platform.</p>
                                    <p>—</p>
                                    <p>ACCESSING, BROWSING, OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THEM CAREFULLY BEFORE PROCEEDING.</p>
                                    <p>The use of the Platform and/or availing of our Services is subject to the following Terms of Use:</p>
                                    <p><strong>1. Accuracy of Information&nbsp;</strong></p>
                                    <p>&nbsp; &nbsp;To access and use the Services, you agree to provide true, accurate, and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.</p>
                                    <p><strong>2. No Warranty&nbsp;</strong></p>
                                    <p>&nbsp;&nbsp; Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness, or suitability of the information and materials offered on this website or through the Services for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors, and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.</p>
                                    <p><strong>3. At Your Own Risk&nbsp;</strong></p>
                                    <p>&nbsp;&nbsp; Your use of our Services and the Platform is solely and entirely at your own risk and discretion, for which we shall not be liable to you in any manner. You are required to independently assess and ensure that the Services meet your requirements.</p>
                                    <p><strong>4. Intellectual Property&nbsp;</strong></p>
                                    <p>&nbsp;&nbsp; The contents of the Platform and the Services are proprietary to us and licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents. The content includes, but is not limited to, the design, layout, look, and graphics.</p>
                                    <p><strong>5. Unauthorized Use&nbsp;</strong></p>
                                    <p>&nbsp;&nbsp; You acknowledge that unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws.</p>
                                    <p><strong>6. Service Charges&nbsp;</strong></p>
                                    <p>&nbsp;&nbsp; You agree to pay us the charges associated with availing the Services.</p>
                                    <p><strong>7. Lawful Use&nbsp;</strong></p>
                                    <p>&nbsp;&nbsp; You agree not to use the Platform and/or Services for any purpose that is unlawful, illegal, or forbidden by these Terms, or by Indian or local laws that might apply to you.</p>
                                    <p><strong>8. Third-Party Links&nbsp;</strong></p>
                                    <p>&nbsp;&nbsp; You acknowledge that the website and Services may contain links to third-party websites. Upon accessing these links, you will be governed by the terms of use, privacy policy, and other policies of such third-party websites. These links are provided for your convenience to provide further information.</p>
                                    <p><strong>9. Legally Binding Contract</strong>&nbsp;</p>
                                    <p>&nbsp;&nbsp; You understand that upon initiating a transaction for availing the Services, you are entering into a legally binding and enforceable contract with the Platform Owner for the Services.</p>
                                    <p><strong>10. Indemnity&nbsp;</strong></p>
                                    <p>&nbsp;&nbsp; You shall indemnify and hold harmless the Platform Owner, its affiliates, group companies (as applicable), and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorneys’ fees, made by any third party or penalty imposed due to or arising out of your breach of these Terms of Use, Privacy Policy, and other Policies, or your violation of any law, rules, or regulations or the rights (including infringement of intellectual property rights) of a third party.</p>
                                    <p><strong>11. Limitation of Liability&nbsp;</strong></p>
                                    <p>&nbsp; &nbsp;In no event will the Platform Owner be liable for any indirect, consequential, incidental, special, or punitive damages, including without limitation, damages for loss of profits or revenues, business interruption, loss of business opportunities, loss of data, or loss of other economic interests, whether in contract, negligence, tort, or otherwise, arising from the use of or inability to use the Services. However, the Platform Owner’s liability will not exceed the amount paid by you for using the Services giving rise to the cause of action or Rupees One Hundred (Rs. 100), whichever is less.</p>
                                    <p><strong>12. Force Majeure&nbsp;</strong></p>
                                    <p>&nbsp;&nbsp; Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event.</p>
                                    <p><strong>13. Governing Law and Jurisdiction&nbsp;</strong></p>
                                    <p>&nbsp;&nbsp; These Terms and any dispute or claim relating to them, or their enforceability, shall be governed by and construed in accordance with the laws of India. All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in North 24 Delhi.</p>
                                    <p><strong>14. Contact Information&nbsp;</strong></p>
                                    <p>&nbsp;&nbsp; All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website.</p>
                                </div>',
            ],
            'Refund & Returns' => [
                'template' => 'default',
                'description' => '<div >
                                    <p><strong>Physical Products<br></strong>-&gt; Orders can be cancelled only before the item is shipped<br>-&gt; Orders already shipped cannot be cancelled</p>
                                    <p><strong>Refund Policy<br></strong><strong>No-Refund Policy</strong><br>We maintain a strict no-refund policy for all products. However, we may make exceptions in the following cases:</p>
                                    <p>-&gt; Product Not Received<br>-&gt; If the product is lost in transit<br>-&gt; If the wrong product is delivered<br>-&gt; If the product is damaged during shipping</p>
                                    <p><strong>Refund Process (When Applicable)<br></strong>If any refund is approved,<strong> t</strong>he amount will be credited back to the original payment method within 7-14 business days<strong><br><br>Return Policy</strong><br><br>We are committed to ensuring customer satisfaction and stand by the quality of our products. Below is our return policy to guide you through the return and replacement process:</p>
                                    <p><strong>Eligibility for Return</strong><br>-&gt; Returns are accepted only for defective, damaged, or incorrect products received.<br>-&gt; The return request must be initiated within 24 hours of receiving the product.</p>
                                    <p><strong>Return Process</strong><br>-&gt; If your return request is approved, the replacement process will be initiated within 2-3 business days.<br>-&gt; Once the replacement is dispatched, it is expected to be delivered within 4-7 business days.</p>
                                    <p><strong>Important Notes</strong><br>-&gt; Delivery timelines may be affected by delays from the transport company, adverse weather conditions, or other unforeseen circumstances.<br>-&gt; We are not responsible for delays caused by external factors beyond our control.</p>
                                    <p>We aim to make the return and replacement process as seamless as possible.</p>
                                </div>',
            ],
            'Shipping Policy' => [
                'template' => 'default',
                'description' => '<div>
                                    <p><strong>Processing Time</strong></p>
                                    <p>All orders are processed within 2-3 business days. During peak periods such as Festival season, processing may take longer, but we will make every effort to ship your order as quickly as possible.</p>
                                    <p><strong>Delivery Time</strong></p>
                                    <p>Delivery times may vary depending on your location. Typically, orders are delivered within 3-7 business days. Please note that delays may occur due to high demand during the festive season or unforeseen circumstances like weather conditions.</p>
                                    <p><strong>Order Tracking</strong></p>
                                    <p>Once your order is shipped, you will receive a tracking number via email, allowing you to track your shipment in real time.</p>
                                    <p></p>
                                </div>',
            ],
            'Sitemap' => [
                'template' => 'default',
                'description' => '',
            ],
            'Thank You' => [
                'template' => 'thankyou',
                'description' => 'Thankyou',
            ],
            'Cart' => [
                'template' => 'cart',
                'description' => '',
            ],
            'Checkout' => [
                'template' => 'checkout',
                'description' => '',
            ],
            'Login' => [
                'template' => 'auth',
                'description' => '',
            ],
            'Register' => [
                'template' => 'auth',
                'description' => '',
            ],
            'Forgot Password' => [
                'template' => 'auth',
                'description' => '',
            ],
            'Reset Password' => [
                'template' => 'auth',
                'description' => '',
            ],
            'Shop' => [
                'template' => 'shop',
                'description' => '',
            ],
            'Category' => [
                'template' => 'category',
                'description' => '',
            ],
            'Order' => [
                'template' => 'order-success-failed',
                'description' => '',
            ],
            
        ];

        foreach ($pages as $title => $data) {

            $slug = Str::slug($title);

            Page::updateOrCreate(
                ['slug' => $slug],
                [
                    'title' => $title,
                    'short_description' => 'Coming soon',
                    'description' => $data['description'] ?? 'Coming soon',
                    'template' => $data['template'] ?? 'default',
                    'status' => true,
                    'author_id' => $author?->id,
                ]
            );

            $this->command->info("✅ Page created/updated: {$title}");
        }
    }
}